# Generated by Django 6.0.7 on 2026-09-10 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodrequest',
            options={'ordering': ['is_fulfilled', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='donorprofile',
            options={'ordering': ['-is_available', '-total_donations', 'user__first_name']},
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='alternate_contact',
            field=models.CharField(blank=True, default='', help_text='Secondary contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_address',
            field=models.CharField(blank=True, default='', help_text='Street address or ward details', max_length=255),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='needed_by',
            field=models.DateField(blank=True, help_text='Target date by which blood is required.', null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Medical details, reason for request, or instructions for donors.'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units_needed',
            field=models.PositiveIntegerField(default=1, help_text='Number of blood bags/units required.'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='urgency',
            field=models.CharField(choices=[('CRITICAL', 'Critical (Within hours)'), ('URGENT', 'Urgent (Within 24 hours)'), ('STANDARD', 'Standard (Within 2-3 days)')], default='URGENT', max_length=10),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short note or medical availability information.'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='total_donations',
            field=models.PositiveIntegerField(default=0, help_text='Total number of completed donations.'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='contact_number',
            field=models.CharField(help_text='Primary phone number to reach the requester/family', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital',
            field=models.CharField(help_text='Name of the hospital or medical clinic.', max_length=200),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='location',
            field=models.CharField(help_text='City / District / Area', max_length=200),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Set whether you are currently available to donate.'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='last_donated',
            field=models.DateField(blank=True, help_text='Date of your last blood donation.', null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
